Feat/creating navbar
amehmeto/CrazyBurger pull request #3
Opened 2022-12-21 21:24 UTC by amehmeto

2022-12-21 21:40 UTC, vileaddev requested changes
Des commentaires par ci et par là concernant des usages courant de naming en frontend.
Penser à destructurer props pour immédiatement faire apparaitre les props dans les propriétés.
Éviter les définition de typage en inline et préférer des typage explicite via un type ou une interface, tout en évitant le type any
Attention au "T" qui pourrait être confondu avec le T de typescript.
Penser aussi à rectifier le rendu de l'UI qui ressemble à la maquette dans l'ensemble mais qui rate certains détails

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/login/components/CrazeeBurgerLogo.tsx
> +import { T } from '../../../reusable-ui/design-system'
```suggestion
import { theme } from '../../../reusable-ui/design-system'
```
Privilégier les nommages explicites comme "theme".
Quand on voit T comme ça, on pense au T du typage dynamique.

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/login/components/LoginForm.tsx
> +import { T } from '../../../reusable-ui/design-system'
pareil ici, theme.

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/NavBar.tsx
> +export function NavBar(props: { firstName: any }) {
```suggestion

interface NavbarProps {
 firstName: string
}
export function NavBar({ firstName } : NavbarProps) {
```

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/NavBar.tsx
> +      <RightSideNavbar firstName={props.firstName} />
```suggestion
      <RightSideNavbar firstName={firstName} />
```

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/NavBar.tsx
> +  function reloadPage() {
à mettre dans un utils global à la racine dans src/

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/NavBar.tsx
> +    return () => window.location.reload()
```suggestion
    window.location.reload()
```

cela suffit largement

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/NavBar.tsx
> +      <CrazeeBurgerLogo onClick={reloadPage()} />
```suggestion
      <CrazeeBurgerLogo onClick={reloadPage} />
```

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/RightSideNavbar.tsx
> +export function RightSideNavbar(props: { firstName: any }) {
créer une interface pour ça (ex: RightSideNavbarProps) et éviter les type any si possible

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/RightSideNavbar.tsx
> +      <div className={'textContainer'}>
enlever les interpolations JSX qui sont inutiles ici. C'est très inhabituel pour une appli React

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/pages/order/components/RightSideNavbar.tsx
> +          Hey, <span>{props.firstName}</span>
```suggestion
          Hey, <span>{firstName}</span>
```

De préférence, destructurer "props" pour extraire d'ores et déjà "les props". C'est plus léger à la lecture et à l'utilisation dans le reste du composant, pour soi et pour ses collègues.

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/reusable-ui/components/PrimaryButton.tsx
>  type PrimaryButtonProps = {
oui 💯

2022-12-21 21:40 UTC, vileaddev commented on frontend/src/reusable-ui/components/TextInput.tsx
> +  onChange?: () => void
https://stackoverflow.com/a/42645711/6463582

2022-12-23 12:35 UTC, vileaddev approved these changes
• Dans l'ensemble c'est OK pour moi 👍 
• Il te reste le style dans LoginPage à changer
• Déplacer des fonctions dans leur propre fichier pour décharger tes composants de "logique métier" réutilisable (ex: formatPrice)

2022-12-23 12:35 UTC, vileaddev commented on src/App.tsx
> +export enum AppRoutes {
Si tu veux être propre, créer un fichier à part que tu peux nommer "routes.js" et là dedans tu défini ton enum que tu rendras exportabe via un "export". Car App doit avoir le moins de logique possible. Limite il n'a que des imports

2022-12-23 12:35 UTC, vileaddev commented on src/pages/ErrorPage.tsx
> +      <p>Tu as fait une erreur maggle</p>
mdrrrrrr !!! 😂 🤣

2022-12-23 12:35 UTC, vileaddev commented on src/pages/login/components/LoginForm.tsx
>        <form onSubmit={accessPrivateSpace}>
je te conseille de repositionner la balise "form" comme balise qui "wrap" tout l'affichage de LoginForm (voir vidéo ci-dessous avec timestamp rajouté)

<img width="997" alt="image" src="https://user-images.githubusercontent.com/110701253/209335501-87b1bf8d-1c3b-4082-b3b9-7a6e295bcacd.png">

2022-12-23 12:35 UTC, vileaddev commented on src/pages/order/OrderPage.tsx
> +import { THEME } from '../../reusable-ui/design-system'
c'est un bon compris de mettre THEME (en majuscule). Variable gloable + nom explicite => tu respectes toutes les conventions, bien pensé 👏 💯

2022-12-23 12:35 UTC, vileaddev commented on src/pages/order/components/RightSideNavbar.tsx
> +export function RightSideNavbar({ firstName }: RightSideNavbarProps) {
yes ! 💯

2022-12-23 12:35 UTC, vileaddev commented on src/pages/order/components/NavBar.tsx
> +  firstName: string | undefined
```suggestion
  firstName?: string
```

est-ce que ces deux écritures sont équivalentes pour toi ?

2022-12-23 12:35 UTC, vileaddev commented on src/pages/order/components/MenuItemCard.tsx
> +  function formatPrice(price: number): string {
c'est une fonction réutilisable. A ce titre, elle n'a rien à faire ici car elle vient d'ailleurs encombrer le composant (cela s'apparent presque à de la logique métier). Conséquemment, il doit bouger vers un dossier (par exemple) "utils/maths.js" dans src/.

2022-12-23 12:35 UTC, vileaddev commented on src/pages/order/components/Main.tsx
> +  useEffect(() => {
Je comprends pourquoi t'as fait ça mais on va éviter de la faire ici, et tu comprendras pourquoi dans la suite du projet. Mais pour le moment, ici, tu n'en as pas besoin. Après, si tu veux le garder pour qu'il soit en concordance avec la promise qui est renvoyée par ton faker, tu peux.

2022-12-23 23:04 UTC, amehmeto commented on src/pages/order/components/NavBar.tsx
> +  firstName: string | undefined
Non c'est deux choses différentes 👍

2022-12-23 23:08 UTC, amehmeto commented on src/pages/order/components/MenuItemCard.tsx
> +  function formatPrice(price: number): string {
Hum, pour l'instant c'est pas réutilisé ou que ce soit, donc c'est pas prouvé.
=> YAGNI

Aussi, dans mon mindset crafteux, `utils` c'est un anti-pattern.

3ème point, un peu tordu certes, mais dans le dev le diable est dans les détails. Cette implémentation du formatage des prix est vrai pour cette page, pas forcément pour une autre. Du coup j'attendrais d'avoir un deuxième usecase pour le faire perso.

2022-12-27 05:05 UTC, amehmeto commented on src/App.tsx
> +export enum AppRoutes {
Pas fan, vu que le fichier App.tsx héberge le composant <Routes> et ses enfants, je préfère avoir l'énumération des routes dans le même fichier, en un coup d'oeil je vois où ça redirige. Une fois n'est pas coutume, je trouve que là ça va ensemble

2022-12-27 05:05 UTC, merged